<?xml version="1.0"?>
<testResults>
  <FitNesseVersion>v20160515</FitNesseVersion>
  <rootPath>TutorialSuitesOfTests.SeleniumFirstTest</rootPath>
    <result>
    <counts>
      <right>0</right>
      <wrong>0</wrong>
      <ignores>0</ignores>
      <exceptions>1</exceptions>
    </counts>
    <date>2016-06-02T14:57:13-04:00</date>
    <runTimeInMillis>5131</runTimeInMillis>
    <content>&lt;br/&gt;&lt;div class="contents"&gt;
	&lt;b&gt;Contents:&lt;/b&gt;
	&lt;ul class="toc1"/&gt;
&lt;/div&gt;
&lt;br/&gt;&lt;br/&gt;&lt;table&gt;
	&lt;tr&gt;
		&lt;td&gt;&lt;span class="fit_SUT"&gt;QaTip.Fitnesse.Demo.DoTestFixture&lt;/span&gt;&lt;/td&gt;
	&lt;/tr&gt;
&lt;/table&gt;
&lt;br/&gt;&lt;table&gt;
	&lt;tr&gt;
		&lt;td class="error" colspan="2"&gt;&lt;span class="fit_member"&gt;UILogIn&lt;/span&gt;&lt;hr /&gt;&lt;pre&gt;&lt;div class="fit_stacktrace"&gt;System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; System.InvalidOperationException: Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. (NoSuchDriver)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.IE.InternetExplorerDriver..ctor(String internetExplorerDriverServerDirectory, InternetExplorerOptions options)
   at QaTip.Fitnesse.Demo.CoreHelpers.InitializeSeleniumBrowser() in c:\Training\Fitnesse\Fixtures\QaTip.Fitnesse.Demo\QaTip.Fitnesse.Demo\CoreHelpers.cs:line 95
   at QaTip.Fitnesse.Demo.DoTestFixture.UILogIn() in c:\Training\Fitnesse\Fixtures\QaTip.Fitnesse.Demo\QaTip.Fitnesse.Demo\DoFixture\DoTestFixture.cs:line 30
   --- End of inner exception stack trace ---
   at fitSharp.Machine.Model.TypedValue.ThrowExceptionIfNotValid()
   at fitSharp.Fit.Engine.InterpretFlow.ProcessFlowRow(Tree`1 table, Int32 rowNumber)&lt;/div&gt;&lt;/pre&gt;&lt;/td&gt;
	&lt;/tr&gt;
	&lt;tr&gt;
		&lt;td&gt;Url&lt;/td&gt;
		&lt;td&gt;navigatetogoogle()&lt;/td&gt;
	&lt;/tr&gt;
	&lt;tr&gt;
		&lt;td&gt;http://google.com&lt;/td&gt;
		&lt;td&gt;&lt;/td&gt;
	&lt;/tr&gt;
&lt;/table&gt;
&lt;br/&gt;</content>
    <relativePageName>SeleniumFirstTest</relativePageName>
          </result>
  <executionLog>
    <testSystem>fit:Fitsharp\Runner.exe</testSystem>
    <command>Fitsharp\Runner.exe -r fitnesse.fitserver.FitServer,FitSharp\fit.dll,FitSharp\fitLibrary.dll -c FitSharp\suite.config.xml ..\Fitnesse\Fixtures\Fitnesse_Dlls\QaTip.Fitnesse.Demo.dll ACNU329C4BY 32985 3863</command>
    <exitCode>1</exitCode>
    <stdOut>6/2/2016 2:57:13 PM: Executing test using Internet Explorer browser.
Started InternetExplorerDriver server (32-bit)
2.53.0.0
Listening on port 32987
Only local connections are allowed
</stdOut>
    <stdErr></stdErr>
  </executionLog>
  <finalCounts>
    <right>0</right>
    <wrong>0</wrong>
    <ignores>0</ignores>
    <exceptions>1</exceptions>
  </finalCounts>
  <totalRunTimeInMillis>5919</totalRunTimeInMillis>
</testResults>

